spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CityGarbage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&useUnicode=false
    username: xier
    password: M2i32%$das

#    username: root
#    password: Abc123456
  session:
    timeout: 50m
server:
  servlet:
    session:
      timeout: 50m
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.healthcare.entity
file:
  upload:
    #    C:\Users\huaqi\Desktop\
    path: /usr/java/tomcat/apache-tomcat-9.0.58/webapps/sk/image/   #文件上传目标路径
    allowTypes: #文件上传允许的类型
      - image/jpeg
      - image/png
      - image/jpg
      - image/bmp
